<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="edu.uoc.mecm.eda.tests.LogTest" tests="3" skipped="0" failures="3" errors="0" timestamp="2022-10-11T13:07:07" hostname="MBP-16-M1-Max-WiFi" time="0.17">
  <properties/>
  <testcase name="Log unit tests" classname="edu.uoc.mecm.eda.tests.LogTest" time="0.163">
    <failure message="Condition not satisfied:&#10;&#10;size1 == 4&#10;|     |&#10;-1    false&#10;" type="org.spockframework.runtime.SpockComparisonFailure">Condition not satisfied:

size1 == 4
|     |
-1    false

	at edu.uoc.mecm.eda.tests.LogTest.Log unit tests(LogTest.groovy:64)
</failure>
  </testcase>
  <testcase name="Test log overflow" classname="edu.uoc.mecm.eda.tests.LogTest" time="0.005">
    <failure message="Expected exception of type 'edu.uoc.mecm.eda.pac1.exercise4.CapacityException', but no exception was thrown" type="org.spockframework.runtime.WrongExceptionThrownError">Expected exception of type 'edu.uoc.mecm.eda.pac1.exercise4.CapacityException', but no exception was thrown
	at org.spockframework.lang.SpecInternals.checkExceptionThrown(SpecInternals.java:80)
	at org.spockframework.lang.SpecInternals.thrownImpl(SpecInternals.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at edu.uoc.mecm.eda.tests.LogTest.Test log overflow(LogTest.groovy:83)
</failure>
  </testcase>
  <testcase name="Test log underflow" classname="edu.uoc.mecm.eda.tests.LogTest" time="0.0">
    <failure message="Expected exception of type 'edu.uoc.mecm.eda.pac1.exercise4.CapacityException', but no exception was thrown" type="org.spockframework.runtime.WrongExceptionThrownError">Expected exception of type 'edu.uoc.mecm.eda.pac1.exercise4.CapacityException', but no exception was thrown
	at org.spockframework.lang.SpecInternals.checkExceptionThrown(SpecInternals.java:80)
	at org.spockframework.lang.SpecInternals.thrownImpl(SpecInternals.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at edu.uoc.mecm.eda.tests.LogTest.Test log underflow(LogTest.groovy:102)
</failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
