<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta http-equiv="x-ua-compatible" content="IE=edge"/>
<title>Test results - Class edu.uoc.mecm.eda.tests.ContainerClusterTest</title>
<link href="../css/base-style.css" rel="stylesheet" type="text/css"/>
<link href="../css/style.css" rel="stylesheet" type="text/css"/>
<script src="../js/report.js" type="text/javascript"></script>
</head>
<body>
<div id="content">
<h1>Class edu.uoc.mecm.eda.tests.ContainerClusterTest</h1>
<div class="breadcrumbs">
<a href="../index.html">all</a> &gt; 
<a href="../packages/edu.uoc.mecm.eda.tests.html">edu.uoc.mecm.eda.tests</a> &gt; ContainerClusterTest</div>
<div id="summary">
<table>
<tr>
<td>
<div class="summaryGroup">
<table>
<tr>
<td>
<div class="infoBox" id="tests">
<div class="counter">6</div>
<p>tests</p>
</div>
</td>
<td>
<div class="infoBox" id="failures">
<div class="counter">6</div>
<p>failures</p>
</div>
</td>
<td>
<div class="infoBox" id="ignored">
<div class="counter">0</div>
<p>ignored</p>
</div>
</td>
<td>
<div class="infoBox" id="duration">
<div class="counter">0.114s</div>
<p>duration</p>
</div>
</td>
</tr>
</table>
</div>
</td>
<td>
<div class="infoBox failures" id="successRate">
<div class="percent">0%</div>
<p>successful</p>
</div>
</td>
</tr>
</table>
</div>
<div id="tabs">
<ul class="tabLinks">
<li>
<a href="#tab0">Failed tests</a>
</li>
<li>
<a href="#tab1">Tests</a>
</li>
</ul>
<div id="tab0" class="tab">
<h2>Failed tests</h2>
<div class="test">
<a name="Cluster methods return exception"></a>
<h3 class="failures">Cluster methods return exception</h3>
<span class="code">
<pre>Expected exception of type 'java.util.NoSuchElementException', but no exception was thrown
	at org.spockframework.lang.SpecInternals.checkExceptionThrown(SpecInternals.java:80)
	at org.spockframework.lang.SpecInternals.thrownImpl(SpecInternals.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at edu.uoc.mecm.eda.tests.ContainerClusterTest.Cluster methods return exception(ContainerClusterTest.groovy:225)
</pre>
</span>
</div>
<div class="test">
<a name="Cluster tests"></a>
<h3 class="failures">Cluster tests</h3>
<span class="code">
<pre>Condition not satisfied:

tsize1 == 2
|      |
-1     false

	at edu.uoc.mecm.eda.tests.ContainerClusterTest.Cluster tests(ContainerClusterTest.groovy:202)
</pre>
</span>
</div>
<div class="test">
<a name="Container tests"></a>
<h3 class="failures">Container tests</h3>
<span class="code">
<pre>Condition not satisfied:

c1ID == &quot;0&quot;
|    |
null false

	at edu.uoc.mecm.eda.tests.ContainerClusterTest.Container tests(ContainerClusterTest.groovy:91)
</pre>
</span>
</div>
<div class="test">
<a name="Service constructor returns exception"></a>
<h3 class="failures">Service constructor returns exception</h3>
<span class="code">
<pre>Expected exception of type 'edu.uoc.mecm.eda.pac1.exercise3.ContainerIPAlreadyBoundException', but no exception was thrown
	at org.spockframework.lang.SpecInternals.checkExceptionThrown(SpecInternals.java:80)
	at org.spockframework.lang.SpecInternals.thrownImpl(SpecInternals.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at edu.uoc.mecm.eda.tests.ContainerClusterTest.Service constructor returns exception(ContainerClusterTest.groovy:160)
</pre>
</span>
</div>
<div class="test">
<a name="Service method setContainers() returns exception"></a>
<h3 class="failures">Service method setContainers() returns exception</h3>
<span class="code">
<pre>Expected exception of type 'edu.uoc.mecm.eda.pac1.exercise3.ContainerIPAlreadyBoundException', but no exception was thrown
	at org.spockframework.lang.SpecInternals.checkExceptionThrown(SpecInternals.java:80)
	at org.spockframework.lang.SpecInternals.thrownImpl(SpecInternals.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at edu.uoc.mecm.eda.tests.ContainerClusterTest.Service method setContainers() returns exception(ContainerClusterTest.groovy:148)
</pre>
</span>
</div>
<div class="test">
<a name="Services tests"></a>
<h3 class="failures">Services tests</h3>
<span class="code">
<pre>Condition not satisfied:

serviceID1 == &quot;10&quot;
|          |
null       false

	at edu.uoc.mecm.eda.tests.ContainerClusterTest.Services tests(ContainerClusterTest.groovy:127)
</pre>
</span>
</div>
</div>
<div id="tab1" class="tab">
<h2>Tests</h2>
<table>
<thead>
<tr>
<th>Test</th>
<th>Duration</th>
<th>Result</th>
</tr>
</thead>
<tr>
<td class="failures">Cluster methods return exception</td>
<td class="failures">0.003s</td>
<td class="failures">failed</td>
</tr>
<tr>
<td class="failures">Cluster tests</td>
<td class="failures">0.038s</td>
<td class="failures">failed</td>
</tr>
<tr>
<td class="failures">Container tests</td>
<td class="failures">0.012s</td>
<td class="failures">failed</td>
</tr>
<tr>
<td class="failures">Service constructor returns exception</td>
<td class="failures">0.003s</td>
<td class="failures">failed</td>
</tr>
<tr>
<td class="failures">Service method setContainers() returns exception</td>
<td class="failures">0.003s</td>
<td class="failures">failed</td>
</tr>
<tr>
<td class="failures">Services tests</td>
<td class="failures">0.055s</td>
<td class="failures">failed</td>
</tr>
</table>
</div>
</div>
<div id="footer">
<p>
<div>
<label class="hidden" id="label-for-line-wrapping-toggle" for="line-wrapping-toggle">Wrap lines
<input id="line-wrapping-toggle" type="checkbox" autocomplete="off"/>
</label>
</div>Generated by 
<a href="http://www.gradle.org">Gradle 5.6</a> at 11 dâ€™oct. 2022, 15:07:08</p>
</div>
</div>
</body>
</html>
